version: '3.1'
services:
  dev-postgres:
    image: postgres
    environment:
      POSTGRES_USER: aozerov
      POSTGRES_PASSWORD: '0112'
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

